image: Visual Studio 2017
clone_folder: 'c:\gopath\src\github.com\%APPVEYOR_REPO_NAME%'

environment:
  # improve readability
  VCS_URL: 'https://github.com/%APPVEYOR_REPO_NAME%'
  # specific to go
  GOPATH: c:\gopath


# prepare system and project
install:
  # install required software
  - choco source add -n=mh-cbon -s="https://api.bintray.com/nuget/mh-cbon/choco"
  - choco install wixtoolset -y
  - refreshenv
  # ensure wix is available in PATH
  - set PATH=%WIX%\bin;%PATH%
  # specific to go
  - set PATH=%GOPATH%\bin;%PATH%

# build msi artifacts
build_script:
  - set GOARCH=amd64
  - go build -o packaging\k6.exe
  - cd packaging
  - candle.exe k6.wxs
  - light.exe -ext WixUIExtension k6.wixobj

# configure the artifacts to upload to the github releae page
artifacts:
  - path: 'packaging\k6.msi'
    name: msi-x64