image: Visual Studio 2017
clone_folder: 'c:\gopath\src\github.com\%APPVEYOR_REPO_NAME%'

# branches:
#   only:
#     - /^v\d+\.\d+\.\d+$/

environment:
  # improve readability
  VCS_URL: 'https://github.com/%APPVEYOR_REPO_NAME%'
  # specific to go
  # VERSION: "%APPVEYOR_REPO_TAG_NAME:v=%"
  VERSION: 0.99.0
  GOPATH: c:\gopath
  BINTRAY_KEY:
    secure: /0S6SdBwfiuWEdY4SKJcZpxEV+QpsfJfqx3QqYbnK8vwmB2KMGqerGzQRnIrkbGD
  GPG_PASSPHRASE:
    secure: CMQ+U+qVVdhIr1Eip5nGPbaGFggVvSjg/BpSY0EpLbQ=


# prepare system and project
install:
  - choco install wixtoolset -y
  - refreshenv
  # ensure wix is available in PATH
  - set PATH=%WIX%\bin;%PATH%
  # specific to go
  - set PATH=%GOPATH%\bin;%PATH%

# build msi artifacts
build_script:
  - set GOARCH=amd64
  - go build -o packaging\k6.exe
  - cd packaging
  - candle.exe -arch x64 -dVERSION=%VERSION% k6.wxs
  - light.exe -ext WixUIExtension k6.wixobj


deploy_script:
  - dir
  - 'curl -H "X-GPG-PASSPHRASE: %GPG_PASSPHRASE%" -T packaging\k6.msi "https://%BINTRAY_USER%:%BINTRAY_KEY%@api.bintray.com/content/loadimpact/windows/k6/%VERSION%/k6-v$VERSION-amd64.msi?publish=1&override=1"'