image: Visual Studio 2017
clone_folder: c:\gopath\src\github.com\%APPVEYOR_REPO_NAME%

# set to false to build on any commit.
skip_non_tags: true

environment:
  # improve readability
  VCS_URL: https://github.com/%APPVEYOR_REPO_NAME%
  GH_APP: %APPVEYOR_PROJECT_NAME%
  GH_USER: %APPVEYOR_ACCOUNT_NAME%
  VERSION: %APPVEYOR_REPO_TAG_NAME%
  # specific to go
  GOPATH: c:\gopath


# prepare system and project
install:
  # install required software
  - choco source add -n=mh-cbon -s="https://api.bintray.com/nuget/mh-cbon/choco"
  - choco install wixtoolset go-msi -y
  - refreshenv
  # ensure wix is available in PATH
  - set PATH=%WIX%\bin;%PATH%
  # specific to go
  - set PATH=%GOPATH%\bin;%PATH%

# build msi artifacts
build_script:
  - set GOARCH=amd64
  - go build -o k6.exe
  - candle.exe packaging\k6.wxs
  - light.exe -ext WixUIExtension packaging\k6.wixobj


# configure the artifacts to upload to the github releae page
artifacts:
  - path: 'k6.msi'
    name: msi-x64